# Generated by Django 4.1.4 on 2023-08-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to=None, verbose_name='E36')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('DateReceived', models.DateField(auto_now_add=True, null=True)),
                ('DateSubmited', models.DateField(auto_now=True, null=True)),
                ('Receivedfrom', models.CharField(max_length=50, verbose_name='Name of te Enginner WhomGive you The E36')),
                ('comments', models.TextField(verbose_name='Comments')),
                ('Duration', models.DurationField(verbose_name='Time Taken To Sole The E36')),
            ],
        ),
    ]
