# Generated by Django 4.1.4 on 2023-08-31 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e36', '0002_quotation_updated_alter_quotation_datesubmited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='File',
            field=models.FileField(null=True, upload_to='', verbose_name='E36'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='TimeRecived',
            field=models.TimeField(null=True, verbose_name='Time Received'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='TimeSubmitted',
            field=models.TimeField(null=True, verbose_name='TimeSubmited'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='Total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='picture'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
    ]
