# Generated by Django 4.1.4 on 2023-08-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e36', '0002_alter_quotation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='Type',
            field=models.CharField(blank=True, choices=[('vpn', 'VPN'), ('internet', 'Leased Line(Fibre)/Internet')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
