# Generated by Django 4.1.4 on 2023-08-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e36', '0003_quotation_type_alter_quotation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='Receivedfrom',
            field=models.CharField(default='Eng', max_length=50, verbose_name='Name of te Enginner WhomGive you The E36'),
        ),
    ]
