# Generated by Django 4.1.4 on 2023-08-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e36', '0004_alter_quotation_receivedfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='Status',
            field=models.CharField(choices=[('Uncompleted', 'Uncompleted'), ('Completed', 'Completed')], max_length=50, null=True, verbose_name='Status of the E36'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='DateReceived',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='DateSubmited',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='Receivedfrom',
            field=models.CharField(default='Enginner ', max_length=50, verbose_name='Name of te Enginner WhomGive you The E36'),
        ),
    ]
