# Generated by Django 4.1.4 on 2023-08-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e36', '0005_quotation_status_alter_quotation_datereceived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='File',
            field=models.FileField(upload_to='e36', verbose_name='E36'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='Type',
            field=models.CharField(blank=True, choices=[('vpn', 'VPN'), ('internet', 'Leased Line(Fibre)/Internet'), ('VoIP', 'VoIP')], max_length=50, null=True),
        ),
    ]
