# Generated by Django 4.1.4 on 2023-09-05 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e36', '0006_remove_quotation_timerecived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='TimeRecived',
            field=models.TimeField(null=True, verbose_name='Time Received'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='TimeSubmitted',
            field=models.TimeField(null=True, verbose_name='TimeSubmited'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
