# Generated by Django 4.1.4 on 2023-08-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e36', '0006_alter_quotation_file_alter_quotation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='Duration',
            field=models.IntegerField(default=0, verbose_name='Time Taken To Sole The E36'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='comments',
            field=models.TextField(null=True, verbose_name='Comments'),
        ),
    ]
