# Generated by Django 4.1.4 on 2023-08-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e36', '0007_alter_quotation_duration_alter_quotation_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='File',
            field=models.FileField(upload_to='', verbose_name='E36'),
        ),
    ]
