# Generated by Django 4.1.4 on 2023-08-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e36', '0008_quotation_created_alter_quotation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='Type',
            field=models.CharField(blank=True, choices=[('VPN', 'VPN'), ('Internet', 'Leased Line(Fibre)/Internet'), ('VoIP', 'VoIP')], max_length=50, null=True),
        ),
    ]
