# Generated by Django 4.1.4 on 2023-08-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e36', '0009_alter_quotation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='created at'),
        ),
    ]
