# Generated by Django 4.1.4 on 2023-09-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Created', models.DateTimeField(auto_now=True, null=True, verbose_name='created at')),
                ('Updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('Extension', models.CharField(blank=True, max_length=10, null=True)),
                ('Department', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
