# Generated by Django 4.1.4 on 2023-08-31 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='', verbose_name='E36')),
                ('NameClient', models.CharField(blank=True, max_length=50, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('Status', models.CharField(choices=[('InProgress', 'Inprogress'), ('Completed', 'Completed')], max_length=50, null=True, verbose_name='Status of the E36')),
                ('Type', models.CharField(blank=True, choices=[('VPN', 'VPN'), ('Internet', 'Leased Line(Fibre)/Internet'), ('VoIP', 'VoIP')], max_length=50, null=True)),
                ('DateReceived', models.DateField(null=True)),
                ('DateSubmited', models.DateField(auto_now_add=True, null=True)),
                ('TimeRecived', models.TimeField(verbose_name='Time Received')),
                ('TimeSubmitted', models.TimeField(verbose_name='TimeSubmited')),
                ('Receivedfrom', models.CharField(default='Enginner ', max_length=50, verbose_name='Name of te Enginner WhomGive you The E36')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('WeekReport', models.IntegerField(null=True, verbose_name='Total amount of e36')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created at')),
                ('image', models.ImageField(blank=True, upload_to='picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
        ),
    ]
