# Generated by Django 4.1.4 on 2023-09-04 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e36', '0004_rename_user_quotation_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(null=True, upload_to='', verbose_name='Documents')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Created', models.DateTimeField(auto_now=True, null=True, verbose_name='created at')),
                ('Updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('Discription', models.TextField(blank=True, null=True, verbose_name='Discription')),
                ('Created_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Who Created The Document')),
            ],
        ),
    ]
