# Generated by Django 4.1.4 on 2023-09-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e36', '0008_alter_quotation_datesubmited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='survey',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
