# Generated by Django 4.2.7 on 2023-11-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e36', '0010_alter_quotation_timerecived_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='Status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], max_length=50, null=True),
        ),
    ]
