# Generated by Django 4.2.7 on 2023-11-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e36', '0012_alter_quotation_weekreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='WeekReport',
            field=models.IntegerField(default=47, null=True, verbose_name='Weekly report'),
        ),
    ]
