# Generated by Django 4.2.7 on 2023-11-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e36', '0015_alter_quotation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='Receivedfrom',
            field=models.CharField(blank=True, choices=[('Dumisani_Mukuchura', 'Dumisani Mukuchura'), ('Jervis_Tsoro', 'Jervis Tsoro'), ('Shylet', 'Shylet'), ('Godwin_Makara', 'Godwin Makara'), ('MAaxwell Mushaikwa', 'Maxwell Mushaikwa '), ('Last Sibasa', 'Last Sibasa')], max_length=50, verbose_name='Name of te Enginner WhomGive you The E36'),
        ),
    ]
