# Generated by Django 4.2.7 on 2023-11-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e36', '0017_alter_quotation_receivedfrom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='survey',
        ),
    ]
