# Generated by Django 4.2.7 on 2023-11-27 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e36', '0019_remove_quotation_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='DateSubmited',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 27, 0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='TimeSubmitted',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='TimeSubmited'),
        ),
    ]
