# Generated by Django 4.2.7 on 2023-11-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e36', '0021_alter_quotation_datesubmited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='WeekReport',
            field=models.IntegerField(null=True, verbose_name='Weekly report'),
        ),
    ]
