# Generated by Django 4.2.7 on 2023-11-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e36', '0022_alter_quotation_weekreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='File',
            field=models.FileField(null=True, unique=True, upload_to='', verbose_name='E36'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='NameClient',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='WeekReport',
            field=models.IntegerField(blank=True, null=True, verbose_name='Weekly report'),
        ),
    ]
