# Generated by Django 4.2.7 on 2023-11-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e36', '0024_alter_quotation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='NameClient',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
