# Generated by Django 4.2.7 on 2023-11-28 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e36', '0025_alter_quotation_nameclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='Receivedfrom',
            field=models.CharField(blank=True, choices=[('Dumisani_Mukuchura', 'Dumisani Mukuchura'), ('Jervis_Tsoro', 'Jervis Tsoro'), ('Shylet', 'Shylet'), ('Godwin_Makara', 'Godwin Makara'), ('MAaxwell_Mushaikwa', 'Maxwell Mushaikwa '), ('Last_Sibasa', 'Last Sibasa'), ('Justice Diba', 'Justice Diba'), ('Christine Mariwo', 'Christine Mariwo')], max_length=50, verbose_name='Name of te Enginner WhomGive you The E36'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='TimeSubmitted',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='TimeSubmited'),
        ),
    ]
