# Generated by Django 4.2.7 on 2023-12-01 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e36', '0026_alter_quotation_receivedfrom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='TimeSubmitted',
            field=models.TimeField(blank=True, default=datetime.time(1, 0), null=True, verbose_name='TimeSubmited'),
        ),
    ]
